name = "lester-apps-auth"
main = "src/index.js"
compatibility_date = "2026-07-12"
preview_urls = false

[vars]
ALLOWED_ORIGIN = "https://lucasj-lab.github.io"
ALLOWED_EMAILS = "jllester.email@gmail.com,enlester1023@gmail.com"
SESSION_TTL_SECONDS = "86400"
GOOGLE_CLIENT_ID = "178682595817-5vodu19d9a0toe5m9qgnjfdu4e17nmob.apps.googleusercontent.com"
APP_DASHBOARD_URL = "https://script.google.com/macros/s/AKfycbwSKt8HR15IGu2et74isjS0v_XpAFkJrS3qHnfHFB3n8yCk_IVd5uuI-KJEmXjgnkwOOQ/exec"
APP_FINANCE_URL = "https://script.google.com/macros/s/AKfycbzQ26Ha10lHHHhKvwD9uF7SlisHOMWhXjJAjti9csTBQxDyBOVk21_gv701G_p6KUwM/exec"
APP_SCHOOL_URL = "https://script.google.com/macros/s/AKfycbx2TjM_l6zhYHlLG9hHAnRX_sy9ld9srRda8FRvUfOkHTup0d1bWyoMLGzwIu1ASfWAKQ/exec"
APP_JOB_URL = "https://script.google.com/macros/s/AKfycbxZ47REtXvEL_ElUoynD9VAQrMrmquLUFUSLVYtN77B1AGz7h1nPDkK80ao-m8NoHmI/exec"
APP_LIFE_URL = "https://script.google.com/macros/s/AKfycbxx_1tugRmXjl0L_ZwavNJLF4g5NG0gPSe6HbDQLZK2Ef7_YDEFo3vucCkeIqzhIgGo/exec"
